### PR TITLE
version up to netcoreapp2.1 because of error when install with 2.1.300

### PR DESCRIPTION
**Pull request by itn3000**

### CODE REVIEW

**Comment by billpratt** [comment]
@itn3000 Can you provide more detaiils. I was able to install the latest on nuget with 2.1.300 installed.

**Comment by billpratt** [comment]
Actually, this shouldnt hurt anything. LGTM

**Comment by billpratt** [comment]
Thanks @itn3000

**Comment by itn3000** [comment]
Thank you for merging.
sorry for my short description.
I installed dotnet-search-0.3.0 on my windows8.1-x64.
and then execute `dotnet search --help`,then get `System.IO.FileNotFoundException`.
[here is my trace file](https://gist.github.com/itn3000/4df523e114b2c5273167448f9108ddbe) with `set COREHOST_TRACE=1`(It's too large to paste here)

**Pull request merged**
